services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tca
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init/insert.sql:/docker-entrypoint-initdb.d/insert.sql
      - "./data:/data"
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge
